barang/urls.py
from django.urls import path
from .views import *
#url for app

app_name = 'barang'
urlpatterns = [
    path('', daftar_barang, name='daftar_barang'),
	path('tambah_barang', tambah_barang, name='tambah_barang'),
    path('<kunci>/detail_barang', detail_barang, name='detail_barang'),
	path('<kunci>/update_barang', update_barang, name='update_barang'),
	path('<kunci>/delete_barang', delete_barang, name='delete_barang')
]

chat/urls.py
from django.urls import path
from .views import *
#url for app

app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    url(r'^pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
    path('barang/', include('barang.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('chat/', include('chat.urls')),
    url(r'^item/', include(('item.urls', 'item'), namespace='item')),
    path('level/', include('level.urls')),
    path('pesanan/', include('pesanan.urls')),
    url(r'pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
]

barang/models.py
from django.db import models

# Create your models here.

barang/views.py
from django.shortcuts import render
from django.db import connection
from django.shortcuts import redirect

# Create your views here.
def daftar_barang(request):
    response = {}

    with connection.cursor() as cursor1:
        cursor1.execute("SELECT * FROM BARANG")
        response["daftar_barang"] = cursor1.fetchall()

    with connection.cursor() as cursor2:
        cursor2.execute("SELECT DISTINCT nama_item FROM BARANG")
        response["filters"] = cursor2.fetchall()
    
    return render(request, 'daftar_barang.html', response)

def tambah_barang(request):
    response = {}

    with connection.cursor() as cursor1:
        cursor1.execute("SELECT DISTINCT nama_item FROM BARANG")
        response["items"] = cursor1.fetchall()

    with connection.cursor() as cursor2:
        cursor2.execute("SELECT DISTINCT P.nama_lengkap FROM PENGGUNA P, BARANG B WHERE B.no_ktp_penyewa = P.no_ktp")
        response["owners"] = cursor2.fetchall()

    if (request.method == "POST"):
        idBarang = request.POST['idBarang']
        namaItem = request.POST['namaItem']
        warna = request.POST['warna']
        urlFoto = request.POST['urlFoto']
        kondisi = request.POST['kondisi']
        lamaPenggunaan = request.POST['lamaPenggunaan']
        pemilik = request.POST['pemilik']
        persenRoyaltyBronze = request.POST['persenRoyaltyBronze']
        hargaSewaBronze = request.POST['hargaSewaBronze']
        persenRoyaltySilver = request.POST['persenRoyaltySilver']
        hargaSewaSilver = request.POST['hargaSewaSilver']
        persenRoyaltyGold = request.POST['persenRoyaltyGold']
        hargaSewaGold = request.POST['hargaSewaGold']

        noKTP = ""
        with connection.cursor() as cursor3:
            cursor3.execute("SELECT no_ktp FROM PENGGUNA WHERE nama_lengap = pemilik")
            noKTP = cursor3.fetchone()[0]


        with connection.cursor() as cursor4:
            cursor4.execute("INSERT INTO BARANG VALUES(%s, %s, %s, %s, %s, %s, %s)", [idBarang, namaItem, warna, urlFoto, kondisi, lamaPenggunaan, noKTP])
            cursor4.execute("INSERT INTO INFO_BARANG_LEVEL VALUES(%s, 'Bronze', %s, %s)", [idBarang, hargaSewaBronze, persenRoyaltyBronze])
            cursor4.execute("INSERT INTO INFO_BARANG_LEVEL VALUES(%s, 'Silver', %s, %s)", [idBarang, hargaSewaSilver, persenRoyaltySilver])
            cursor4.execute("INSERT INTO INFO_BARANG_LEVEL VALUES(%s, 'Gold', %s, %s)", [idBarang, hargaSewaGold, persenRoyaltyGold])

        return redirect("/barang/")

    return render(request, 'tambah_barang.html', response)

def update_barang(request, kunci):
    response = {}

    with connection.cursor() as cursor1:
        cursor1.execute("SELECT DISTINCT nama_item FROM BARANG")
        response["items"] = cursor1.fetchall()

    with connection.cursor() as cursor2:
        cursor2.execute("SELECT DISTINCT P.nama_lengkap FROM PENGGUNA P, BARANG B WHERE B.no_ktp_penyewa = P.no_ktp")
        response["owners"] = cursor2.fetchall()

    if (request.method == "POST"):
        idBarang = request.POST['idBarang']
        namaItem = request.POST['namaItem']
        warna = request.POST['warna']
        urlFoto = request.POST['urlFoto']
        kondisi = request.POST['kondisi']
        lamaPenggunaan = request.POST['lamaPenggunaan']
        pemilik = request.POST['pemilik']
        persenRoyaltyBronze = request.POST['persenRoyaltyBronze']
        hargaSewaBronze = request.POST['hargaSewaBronze']
        persenRoyaltySilver = request.POST['persenRoyaltySilver']
        hargaSewaSilver = request.POST['hargaSewaSilver']
        persenRoyaltyGold = request.POST['persenRoyaltyGold']
        hargaSewaGold = request.POST['hargaSewaGold']

        noKTP = ""
        with connection.cursor() as cursor3:
            cursor3.execute("SELECT no_ktp FROM PENGGUNA WHERE nama_lengap = pemilik")
            noKTP = cursor3.fetchone()[0]

        with connection.cursor() as cursor4:
            cursor4.execute("UPDATE BARANG SET nama_item = %s, warna = %s, url_foto = %s, kondisi = %s, lama_penggunaan = %s, no_ktp_penyewa = %s  WHERE id_barang = %s", [namaItem, warna, urlFoto, kondisi, lamaPenggunaan, noKTP, idBarang])
            cursor4.execute("UPDATE INFO_BARANG_LEVEL SET harga_sewa = %s, porsi_loyalti = %s  WHERE id_barang = %s AND nama_level = 'Bronze'", [hargaSewaBronze, persenRoyaltyBronze, idBarang])
            cursor4.execute("UPDATE INFO_BARANG_LEVEL SET harga_sewa = %s, porsi_loyalti = %s  WHERE id_barang = %s AND nama_level = 'Silver'", [hargaSewaSilver, persenRoyaltySilver, idBarang])
            cursor4.execute("UPDATE INFO_BARANG_LEVEL SET harga_sewa = %s, porsi_loyalti = %s  WHERE id_barang = %s AND nama_level = 'Gold'", [hargaSewaGold, persenRoyaltyGold, idBarang])
        return redirect("/barang/")

    data_barang = []
    with connection.cursor() as cursor5:
        cursor5.execute("SELECT * FROM BARANG WHERE id_barang = %s", [kunci])
        data_barang = cursor5.fetchone()

    data_bronze = []
    with connection.cursor() as cursor6:
        cursor6.execute("SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s AND nama_level = 'Bronze'", [kunci])
        data_bronze = cursor6.fetchone()
    
    data_silver = []
    with connection.cursor() as cursor7:
        cursor7.execute("SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s AND nama_level = 'Silver'", [kunci])
        data_silver = cursor7.fetchone()

    data_gold = []
    with connection.cursor() as cursor8:
        cursor8.execute("SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s AND nama_level = 'Gold'", [kunci])
        data_gold = cursor8.fetchone()

    response["id_barang"] = data_barang[0]
    response["nama_item"] = data_barang[1]
    response["warna"] = data_barang[2]
    response["url_foto"] = data_barang[3]
    response["kondisi"] = data_barang[4]
    response["lama_penggunaan"] = data_barang[5]

    with connection.cursor() as cursor9:
        cursor9.execute("SELECT nama_lengkap FROM PENGGUNA WHERE no_ktp = %s", [data_barang[6]])
        response["nama_pemilik"] = cursor9.fetchone()[0]

    response["harga_sewa_bronze"] = data_bronze[2]
    response["porsi_loyalti_bronze"] = data_bronze[3]
    response["harga_sewa_silver"] = data_silver[2]
    response["porsi_loyalti_silver"] = data_silver[3]
    response["harga_sewa_gold"] = data_gold[2]
    response["porsi_loyalti_gold"] = data_gold[3]

    return render(request, 'update_barang.html', response)

def delete_barang(request, kunci):
	with connection.cursor() as cursor:
		cursor.execute("DELETE FROM BARANG WHERE id_barang = %s", [kunci])
	return redirect("/barang/")

def detail_barang(request, kunci):
    response = {}

    with connection.cursor() as cursor1:
        cursor1.execute("SELECT P.nama_lengkap, BD.review FROM BARANG_DIKIRIM BD, PENGIRIMAN PN , PENGGUNA P WHERE BD.id_barang = %s AND BD.no_resi = PN.no_resi AND PN.no_ktp_anggota = P.no_ktp", [kunci])
        response["daftar_review"] = cursor1.fetchall()

    data_barang = []
    with connection.cursor() as cursor5:
        cursor5.execute("SELECT * FROM BARANG WHERE id_barang = %s", [kunci])
        data_barang = cursor5.fetchone()

    data_bronze = []
    with connection.cursor() as cursor6:
        cursor6.execute("SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s AND nama_level = 'Bronze'", [kunci])
        data_bronze = cursor6.fetchone()
    
    data_silver = []
    with connection.cursor() as cursor7:
        cursor7.execute("SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s AND nama_level = 'Silver'", [kunci])
        data_silver = cursor7.fetchone()

    data_gold = []
    with connection.cursor() as cursor8:
        cursor8.execute("SELECT * FROM INFO_BARANG_LEVEL WHERE id_barang = %s AND nama_level = 'Gold'", [kunci])
        data_gold = cursor8.fetchone()

    response["id_barang"] = data_barang[0]
    response["nama_item"] = data_barang[1]
    response["warna"] = data_barang[2]
    response["url_foto"] = data_barang[3]
    response["kondisi"] = data_barang[4]
    response["lama_penggunaan"] = data_barang[5]

    with connection.cursor() as cursor9:
        cursor9.execute("SELECT nama_lengkap FROM PENGGUNA WHERE no_ktp = %s", [data_barang[6]])
        response["nama_pemilik"] = cursor9.fetchone()[0]

    response["harga_sewa_bronze"] = data_bronze[2]
    response["porsi_loyalti_bronze"] = data_bronze[3]
    response["harga_sewa_silver"] = data_silver[2]
    response["porsi_loyalti_silver"] = data_silver[3]
    response["harga_sewa_gold"] = data_gold[2]
    response["porsi_loyalti_gold"] = data_gold[3]

    return render(request, 'detail_barang.html', response)

barang/templates/daftar_barang.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mt-5">
    <nav class="m-3 pr-md-2">
        <nav class="container-fluid p-3" style="background: #1BCC8C; color: white;">
            <h1 class="display-5">Daftar Barang</h1>
        </nav>
    </nav>

    <nav class="m-3 pr-md-2" id="daftarBarang">
        <nav class="container-fluid p-0">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary" type="button" onclick="filter()">Filter</button>
                </div>
                <select class="custom-select" id="filterItem">
                    <option selected>Semua</option>
                    {% for filter in filters %}
                    <option>{{ filter.0 }}</option>
                    {% endfor %}
                </select>
            </div>
            <table class="table table table-striped table-responsive-sm" id="myTable">
                <thead>
                    <tr>
                        <th scope="col" onclick="sortTable(0)"><a href="#" class="text-body">Id Barang</a></th>
                        <th scope="col" onclick="sortTable(1)"><a href="#" class="text-body">Nama Item</a></th>
                        <th scope="col">Warna</th>
                        <th scope="col">Kondisi</th>
                        <th scope="col">Detail</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody id="isiBarang">
                    {% for barang in daftar_barang %}
                    <tr>
                        <th scope="row" id="id">{{ barang.0 }}</th>
                        <td id="nama">{{ barang.1 }}</td>
                        <td id="warna">{{ barang.2 }}</td>
                        <td id="kondisi">{{ barang.4 }}</td>
                        <td>
                            <a href="{% url 'barang:detail_barang' kunci=barang.0 %}">
                                <button type="button" class="btn btn-info btn-sm">Detail</button>
                            </a>
                        </td>
                        <td>
                            {% if request.session.role == "Admin" %}
                            <a href="{% url 'barang:update_barang' kunci=barang.0 %}">
                                <button class="btn btn-primary btn-sm">Update</button>
                            </a>
                            <a href="{% url 'barang:delete_barang' kunci=barang.0 %}">
                                <button class="btn btn-danger btn-sm" id="delete" data-toggle="modal" data-target="#delete-modal">Delete</button>
                            </a>
                            {% else %}
                            <div class="form-check">
                                <input class="form-check-input mx-auto checkPesan" type="checkbox">
                            </div>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <nav class="float-right">
                <ul class="pagination" style="background: inherit;">
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">1<span class="sr-only">(current)</span></span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
            <button class="btn btn-primary sr-only float-left" id="pesan" type ="button">Pesan</button>
        </nav>
    </nav>    
</div>
{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'js/daftar_barang.js' %}"></script>
<script>
    function sortTable(n) {
    var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
    table = document.getElementById("myTable");
    switching = true;
    //Set the sorting direction to ascending:
    dir = "asc"; 
    /*Make a loop that will continue until
    no switching has been done:*/
    while (switching) {
        //start by saying: no switching is done:
        switching = false;
        rows = table.rows;
        /*Loop through all table rows (except the
        first, which contains table headers):*/
        for (i = 1; i < (rows.length - 1); i++) {
        //start by saying there should be no switching:
        shouldSwitch = false;
        /*Get the two elements you want to compare,
        one from current row and one from the next:*/
        x = rows[i].getElementsByTagName("TD")[n];
        y = rows[i + 1].getElementsByTagName("TD")[n];
        /*check if the two rows should switch place,
        based on the direction, asc or desc:*/
        if (dir == "asc") {
            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
            //if so, mark as a switch and break the loop:
            shouldSwitch= true;
            break;
            }
        } else if (dir == "desc") {
            if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
            //if so, mark as a switch and break the loop:
            shouldSwitch = true;
            break;
            }
        }
        }
        if (shouldSwitch) {
        /*If a switch has been marked, make the switch
        and mark that a switch has been done:*/
        rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
        switching = true;
        //Each time a switch is done, increase this count by 1:
        switchcount ++;      
        } else {
        /*If no switching has been done AND the direction is "asc",
        set the direction to "desc" and run the while loop again.*/
        if (switchcount == 0 && dir == "asc") {
            dir = "desc";
            switching = true;
        }
        }
    }
    }

    function filter() {
    var input, filter, table, tr, td, i, txtValue, no;
    no = document.getElementById("filterItem");
    input = no.options[no.selectedIndex].text;
    if (input == "Semua") input = "";
    filter = input.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
        } else {
            tr[i].style.display = "none";
        }
        }       
    }
    }

    // function hapusBarang(n) {
    // if (confirm("Anda yakin ingin menghapus barang?")) {
    //     var i = n.parentNode.parentNode.rowIndex;
    //     document.getElementById("myTable").deleteRow(i);
    // }
    // }
</script>
{% endblock %}

barang/templates/detail_barang.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mt-5">
    <nav class="m-3 pr-md-2">
        <nav class="container-fluid p-3" style="background: #1BCC8C; color: white;">
            <h1 class="display-5">Detail Barang</h1>
        </nav>
    </nav>
    <dl class="row m-3">
        <dt class="col-sm-3">Id Barang</dt>
        <dd class="col-sm-9">{{ id_barang }}</dd>

        <dt class="col-sm-3">Nama Item</dt>
        <dd class="col-sm-9">{{ nama_item }}</dd>

        <dt class="col-sm-3">Warna</dt>
        <dd class="col-sm-9">{{ warna }}</dd>

        <dt class="col-sm-3">URL Foto</dt>
        <dd class="col-sm-9"><i>{{ url_foto }}</i></dd>

        <dt class="col-sm-3">Kondisi</dt>
        <dd class="col-sm-9">{{ kondisi }}</dd>

        <dt class="col-sm-3">Lama Penggunaan</dt>
        <dd class="col-sm-9">{{ lama_penggunaan }}</dd>

        <dt class="col-sm-3">Pemilik/Penyewa</dt>
        <dd class="col-sm-9">{{ nama_pemilik }}</dd>

        <br>

        <dt class="col-sm-3">Info Barang</dt>
        <dd class="col-sm-9"></dd>
        
        <dt class="col-sm-3">Bronze</dt>
        <dd class="col-sm-9">
            <dl class="row">
            <dt class="col-sm-4">Persen Royalty</dt>
            <dd class="col-sm-8">{{ porsi_loyalti_bronze }}</dd>
            </dl>
            <dl class="row">
            <dt class="col-sm-4">Harga Sewa</dt>
            <dd class="col-sm-8">{{ harga_sewa_bronze }}</dd>
            </dl>
        </dd>

        <dt class="col-sm-3">Silver</dt>
        <dd class="col-sm-9">
            <dl class="row">
            <dt class="col-sm-4">Persen Royalty</dt>
            <dd class="col-sm-8">{{ porsi_loyalti_silver }}</dd>
            </dl>
            <dl class="row">
            <dt class="col-sm-4">Harga Sewa</dt>
            <dd class="col-sm-8">{{ harga_sewa_silver }}</dd>
            </dl>
        </dd>

        <dt class="col-sm-3">Gold</dt>
        <dd class="col-sm-9">
            <dl class="row">
            <dt class="col-sm-4">Persen Royalty</dt>
            <dd class="col-sm-8">{{ porsi_loyalti_gold }}</dd>
            </dl>
            <dl class="row">
            <dt class="col-sm-4">Harga Sewa</dt>
            <dd class="col-sm-8">{{ harga_sewa_gold }}</dd>
            </dl>
        </dd>

        <br>

        <dt class="col-sm-3">Review</dt>
        <dd class="col-sm-9"></dd>

        {% for review in daftar_review %}
        <dt class="col-sm-3">{{ review.0 }}</dt>
        <dd class="col-sm-9"><i>{{ review.1 }}</i></dd>
        {% endfor %}

        <br>

        <button class="btn btn-primary float-left" id="pesan" type ="button">Pesan</button>
    </dl>
</div>
{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock %}

barang/templates/tambah_barang.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card mt-5">
    <h5 class="card-header text-center py-4" style="background: #1BCC8C; color: white;">
        <strong>FORM PENAMBAHAN BARANG</strong>
    </h5>

    <!--Card content-->
    <div class="card-body px-lg-5 pt-0">
        
        <!-- Form -->
        <form class="px-2 mx-auto col-md-6" style="color: #1BCC8C;" id="form-registration">
            {% csrf_token %}

            <!-- Id Barang -->
            <div class="md-form mt-3">
                <label for="idBarang">Id Barang</label>
                <input type="text" id="idBarang" class="form-control" required>
                <div class="invalidId"></div>
            </div>

            <!-- Nama Item -->
            <div class="form-group mt-3">
                <label for="inputProgramName">Nama Item</label>
                <select class="form-control" id="namaItem">
                    <option value="" disabled selected>Pilih item</option>
                    {% for item in items %}
                    <option>{{ item.0 }}</option>
                    {% endfor %}
                </select>
                <div class="invalidItem"></div>
            </div>

            <!-- Warna -->
            <div class="md-form mt-3">
                <label for="warna">Warna</label>
                <input type="text" id="warna" class="form-control">
            </div>

            <!-- URL Foto -->
            <div class="md-form mt-3">
                <label for="urlFoto">URL Foto</label>
                <input type="text" id="urlFoto" class="form-control">
            </div>

            <!-- Kondisi -->
            <div class="md-form mt-3">
                <label for="kondisi">Kondisi</label>
                <input type="text" id="kondisi" class="form-control" required>
                <div class="invalidKondisi"></div>
            </div>

            <!-- Lama Penggunaan -->
            <div class="md-form mt-3">
                <label for="lamaPenggunaan">Lama Penggunaan</label>
                <input type="number" id="lamaPenggunaan" class="form-control" min="1" max="1000000000">
                <small id="lamaPenggunaanHelp" class="form-text text-muted mb-4">Dalam bulan</small>
            </div>

            <!-- Pemilik/Penyewa -->
            <div class="form-group mt-3">
                <label for="inputProgramName">Pemilik/Penyewa</label>
                <select class="form-control" id="pemilik">
                    <option value="" disabled selected>Pilih pemilik/penyewa</option>
                    {% for owner in owners %}
                    <option>{{ owner.0 }}</option>
                    {% endfor %}
                </select>
                <div class="invalidPemilik"></div>
            </div>

            <!-- Info Barang -->
            <p class="h4 mt-5">Info Barang</p>

            <!--Bronze-->
            <p class="h5 mt-3">Bronze</p>
            <div class="form-row mt-1">
                <div class="col">
                    <!-- Persen Royalty -->
                    <div class="md-form">
                        <label for="persenRoyaltyBronze">Persen Royalty</label>
                        <input type="number" id="persenRoyaltyBronze" class="form-control" min="0" max="100">
                        <small id="persenRoyaltyBronzeHelp" class="form-text text-muted mb-4">Dalam persen</small>
                    </div>
                </div>
                <div class="col">
                    <!-- Harga Sewa -->
                    <div class="md-form">
                        <label for="hargaSewaBronze">Harga Sewa</label>
                        <input type="number" id="hargaSewaBronze" class="form-control" min="0" max="10000000">
                        <small id="persenRoyaltyBronzeHelp" class="form-text text-muted mb-4">Dalam Rupiah/minggu</small>
                    </div>
                </div>
            </div>

            <!--Silver-->
            <p class="h5 mt-3">Silver</p>
            <div class="form-row mt-1">
                <div class="col">
                    <!-- Persen Royalty -->
                    <div class="md-form">
                        <label for="persenRoyaltySilver">Persen Royalty</label>
                        <input type="number" id="persenRoyaltySilver" class="form-control" min="0" max="100">
                        <small id="persenRoyaltySilverHelp" class="form-text text-muted mb-4">Dalam persen</small>
                    </div>
                </div>
                <div class="col">
                    <!-- Harga Sewa -->
                    <div class="md-form">
                        <label for="hargaSewaSilver">Harga Sewa</label>
                        <input type="number" id="hargaSewaSilver" class="form-control" min="0" max="10000000">
                        <small id="persenRoyaltySilverHelp" class="form-text text-muted mb-4">Dalam Rupiah/minggu</small>
                    </div>
                </div>
            </div>

            <!--Gold-->
            <p class="h5 mt-3">Gold</p>
            <div class="form-row mt-1">
                <div class="col">
                    <!-- Persen Royalty -->
                    <div class="md-form">
                        <label for="persenRoyaltyGold">Persen Royalty</label>
                        <input type="number" id="persenRoyaltyGold" class="form-control" min="0" max="100">
                        <small id="persenRoyaltyGoldHelp" class="form-text text-muted mb-4">Dalam persen</small>
                    </div>
                </div>
                <div class="col">
                    <!-- Harga Sewa -->
                    <div class="md-form">
                        <label for="hargaSewaGold">Harga Sewa</label>
                        <input type="number" id="hargaSewaGold" class="form-control" min="0" max="10000000">
                        <small id="persenRoyaltyGoldHelp" class="form-text text-muted mb-4">Dalam Rupiah/minggu</small>
                    </div>
                </div>
            </div>

            <!-- Send button -->
            <button class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4 waves-effect" id="submit" type ="submit">Submit</button>

        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'js/tambah_barang.js' %}"></script>
{% endblock %}