chat/urls.py
from django.urls import path
from .views import *
#url for app

app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
]

pesanan/urls.py
from django.urls import path
from pesanan import views

app_name = 'pesanan'
urlpatterns = [
	path('', views.daftar_pesanan, name='daftar_pesanan'),
    path('buat_pesanan', views.buat_pesanan, name='buat_pesanan'),
    path('<int:pk>/update', views.update_pesanan, name='update_pesanan')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    url(r'^pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
    path('barang/', include('barang.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('chat/', include('chat.urls')),
    url(r'^item/', include(('item.urls', 'item'), namespace='item')),
    path('level/', include('level.urls')),
    path('pesanan/', include('pesanan.urls')),
    url(r'pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
]

pesanan/models.py
from django.db import models

# Create your models here.

pesanan/views.py
from django.shortcuts import render
from django.db import connection
from django.shortcuts import redirect
import datetime

# Create your views here.
def daftar_pesanan(request):
	response = {}
	content = {}
	data_pesanan = []
	sql = "SELECT P.id_pemesanan, R.nama_item, P.harga_sewa, S.nama AS STATUS FROM PEMESANAN P JOIN STATUS S ON S.nama = P.status JOIN BARANG_PESANAN B ON B.id_pemesanan = P.id_pemesanan JOIN BARANG R ON R.id_barang = B.id_barang"

	if request.session["role"] == "Admin":
		with connection.cursor() as cursor:
			cursor.execute(sql)
			data_pesanan = cursor.fetchall()
	elif request.session["role"] == "Anggota":
		with connection.cursor() as cursor:
			sql = sql + " WHERE P.no_ktp_pemesan = %s"
			cursor.execute(sql, [request.session["no_ktp"]])
			data_pesanan = cursor.fetchall()

	for data in data_pesanan:
		if data[0] in response.keys():
			response[data[0]]["barang"].append(data[1])
		else:
			response[data[0]] = {}
			response[data[0]]["id_pemesanan"] = data[0]
			response[data[0]]["barang"] = [data[1]]
			response[data[0]]["harga"] = data[2]
			response[data[0]]["status"] = data[3]

	content["response"] = response
	return render(request, 'daftar_pesanan.html', content)

def buat_pesanan(request):
	response = {}
	current_id_pemesanan = 0

	if (request.method == "POST"):

		with connection.cursor() as cursor:
			sql = "SELECT P.id_pemesanan FROM PEMESANAN P"
			cursor.execute(sql)
			ids = cursor.fetchall()
			for id in ids:
				if int(id[0]) > current_id_pemesanan:
					current_id_pemesanan = int(id[0])

			id_pemesanan = current_id_pemesanan + 1
			no_ktp = request.POST["no_ktp_anggota"]
			id_barang = request.POST.getlist("id_barang")
			kuantitas = len(id_barang)
			lama_sewa = request.POST["lama_sewa"]
			waktu = datetime.datetime.now()
			tanggal = datetime.date.today()
			cursor.execute("INSERT INTO PEMESANAN(id_pemesanan, datetime_pesanan, kuantitas_barang, no_ktp_pemesan, status) VALUES(%s, %s, %s, %s, %s)", [id_pemesanan, waktu, kuantitas, no_ktp, "SEDANG_DIKONFIRMASI"])
			for i in range(len(id_barang)):
				cursor.execute(
					"INSERT INTO BARANG_PESANAN(id_pemesanan, no_urut, id_barang, tanggal_sewa, lama_sewa, status) VALUES(%s, %s, %s, %s, %s, %s)",
					[id_pemesanan, i, id_barang[i], tanggal, lama_sewa, "SEDANG_DIKONFIRMASI"])

		return redirect("/pesanan/")

	with connection.cursor() as cursor:
		cursor.execute("SELECT P.no_ktp, P.nama_lengkap FROM ANGGOTA A JOIN PENGGUNA P ON A.no_ktp = P.no_ktp")
		anggota = cursor.fetchall()
		response["anggota"] = anggota

		cursor.execute("SELECT I.nama, B.id_barang FROM BARANG B JOIN ITEM I ON I.nama = B.nama_item")
		barang = cursor.fetchall()
		response["barang"] = barang

	return render(request, 'buat_pesanan.html', response)

def update_pesanan(request, pk):
	data = {}
	response = {}

	if (request.method == "POST"):
		with connection.cursor() as cursor:
			id_barang = request.POST.getlist("id_barang")
			status = request.POST["konfirm"]
			cursor.execute(
				"UPDATE PEMESANAN SET status = %s WHERE id_pemesanan = CAST(%s AS varchar)",
				[status, pk])
			cursor.execute(
				"DELETE FROM PEMESANAN WHERE id_pemesanan = CAST(%s AS varchar)", [pk])
			for i in range(len(id_barang)):
				cursor.execute(
					"INSERT INTO BARANG_PESANAN(id_pemesanan, no_urut, id_barang, tanggal_sewa, lama_sewa, status) VALUES(%s, %s, %s, %s, %s, %s)",
					[pk, i, id_barang[i], datetime.date.today(), lama_sewa, status])

		return redirect("/pesanan/")

	with connection.cursor() as cursor:
		cursor.execute("SELECT I.nama, B.id_barang FROM BARANG B JOIN ITEM I ON I.nama = B.nama_item")
		barang = cursor.fetchall()
		data["barang"] = barang
		cursor.execute("SELECT id_barang FROM BARANG_PESANAN WHERE id_pemesanan = CAST(%s AS varchar)", [pk])
		id_barang = cursor.fetchall()
		cursor.execute("SELECT lama_sewa FROM BARANG_PESANAN WHERE id_pemesanan = CAST(%s AS varchar)", [pk])
		lama_sewa = cursor.fetchone()
		cursor.execute("SELECT status FROM PEMESANAN WHERE id_pemesanan = CAST(%s AS varchar)", [pk])
		status = cursor.fetchone()

	data["pk"] = pk
	data["status"] = status[0]
	data["lama_sewa"] = lama_sewa[0]
	data["id_barang"] = id_barang
	print(data)
	return render(request, 'update_pesanan.html', data)

pesanan/templates/buat_pesanan.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'pesanan/css/style.css' %}">
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
{% endblock %}
{% block content %}
<body id="buat_pesanan">
		<div class="col-xs-12 container">
			<form id="form_pesanan" action="{% url 'pesanan:buat_pesanan' %}" method="POST">
				{% csrf_token %}
				<h1 class="title text-white">Ayo Pesan Mainan Favoritmu!</h1>
				<br>
				<br>

				<!--apapun lah ini filternya masih sembarangan, tergantung fitur 1-->
				{% if request.session.role == "Admin" %}
				<select class="col-md-6 form-control" type="text" name="no_ktp_anggota" placeholder="Anggota">
					{% for ang in anggota %}
					<option value={{ ang.0 }}>{{ ang.1 }}</option>
					{% endfor %}
				</select>
				<br>
				<br>
				<br>
				{% endif %}
				<select class="col-md-6 form-control" type="text" name="id_barang" placeholder="Barang" multiple>
					{% for bar in barang %}
					<option value={{ bar.1 }}>{{ bar.0 }}</option>
					{% endfor %}
				</select>
				<small>Press control for multiselect</small>
				<br>
				<br>
				<br>
				<input class="col-md-6 form-control" type="number" name="lama_sewa" placeholder="Berapa hari akan menyewa?">
				<br>
				<button class="btn btn-green" type="submit" value="Submit">Buat</button>
			</form>
		</div>
	</body>
{% endblock %}

pesanan/templates/daftar_pesanan.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'pesanan/css/style.css' %}">
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
{% endblock %}
{% block content %}
<div class="col-xs-12 container">
	<h1 class="title">Daftar Pesanan</h1>
	<br>
	<br>
	<table class="table">
		<thead>
		<tr>
			<th>Id pemesanan</th>
			<th>Daftar barang</th>
			<th>Harga</th>
			<th>Status</th>
			<th>Edit</th>
			{% if request.session.role == "Anggota" %}
			<th>Delete</th>
			{% endif %}
		<tr>
		</thead>

		<tbody id="data_pesanan">
		{% for id, pesanan in response.items %}
			<tr id={{ pesanan.id_pemesanan }}>
				<td id="id_pemesanan">{{ pesanan.id_pemesanan }}</td>
				<td id="barang">
					<ul style="background-color: transparent">
						{% for barang in pesanan.barang %}
						<li>{{ barang }}</li>
						{% endfor %}
					</ul>
				</td>
				<td id="harga">{{ pesanan.harga }}</td>
				<td id="status">{{ pesanan.status }}</td>
				<td><a href="{% url 'pesanan:update_pesanan' pk=pesanan.id_pemesanan %}"><button class="btn btn-icon btn-info"><i class="fa fa-keyboard"></i></button></a></td>
				{% if request.session.role == "Anggota" %}
				<td><button data-toggle="modal" data-target="#delete-modal" class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></td>
				{% endif %}
			</tr>
		{% endfor %}
		</tbody>
	</table>

	<div class="modal" id="delete-modal">
		<div class="modal-dialog">
			<div class="modal-content">

				<div class="modal-body">
					Apakah anda yakin ingin delete?
				</div>

				<!-- Modal footer -->
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">Ya!</button>
					<button type="button" class="btn btn-danger" data-dismiss="modal">Ga!</button>
				</div>

			</div>
		</div>
	</div>
</div>
{% endblock %}

pesanan/templates/update_pesanan.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'pesanan/css/style.css' %}">
    	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
{% endblock %}
{% block content %}
<body id="buat_pesanan">
		<div class="col-xs-12 container">
			<form id="form_pesanan" action="{% url 'pesanan:update_pesanan' pk=pk %}" method="POST">
				{% csrf_token %}
				<h1 class="title text-white">Ayo Pesan Mainan Favoritmu!</h1>
				<br>
				<br>

				<!--apapun lah ini filternya masih sembarangan, tergantung fitur 1-->
				<select class="col-md-6 form-control" type="text" name="id_barang" placeholder="Barang" multiple>
					{% for bar in barang %}
					<option value={{ bar.1 }}>{{ bar.0 }}</option>
					{% endfor %}
				</select>
				<small>Press control for multiselect</small>
				<br>
				<br>
				<input class="col-md-6 form-control" type="text" name="lama_sewa" value={{ lama_sewa }}>
				<br>
				{% if request.session.role == "Admin" %}
				<select class="col-md-6 form-control" type="text" name="konfirm" value={{ status }} placeholder="Konfirm">
					<option value="MENUNGGU_PEMBAYARAN">Konfirm</option>
					<option value="SEDANG_DIKONFIRMASI">Jangan</option>
				</select>
				{% endif %}
				{% if request.session.role == "Anggota" %}
					<p id="status">Status : {{ obj.status }}</p>
				{% endif %}
				<br>
				<button class="btn btn-green" type="submit" value="Submit">Update</button>
			</form>
		</div>
	</body>
{% endblock %}