chat/urls.py
from django.urls import path
from .views import *
#url for app

app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
]

level/urls.py
from django.urls import path
from level import views

app_name = 'level'
urlpatterns = [
	path('', views.daftar_level, name='list_level'),
	path('add', views.tambah_level, name='add_level'),
	path('<nama>/update', views.update_level, name='update_level'),
	path('<nama>/delete', views.delete_level, name='delete_level')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    url(r'^pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
    path('barang/', include('barang.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('chat/', include('chat.urls')),
    url(r'^item/', include(('item.urls', 'item'), namespace='item')),
    path('level/', include('level.urls')),
    path('pesanan/', include('pesanan.urls')),
    url(r'pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
]

level/models.py
from django.db import models

# Create your models here.

level/forms.py
from django import forms

class LevelForm(forms.Form):
    nama_level = forms.CharField(label='Nama Level', widget=forms.TextInput(attrs={'class': 'form-control col-md-6',
        'id': 'nama-level', 'placeholder': "Nama Level"}))

    min_poin = forms.IntegerField(label='Minimum Poin', widget=forms.NumberInput(attrs={'class': 'form-control col-md-6',
        'id': 'min-point', 'placeholder': "Minimum Poin"}))

    deskripsi = forms.CharField(label='Deskripsi', widget=forms.TextInput(attrs={'class': 'form-control col-md-6',
                                                                'id': 'deskripsi', 'placeholder': "Deskripsi"}))

level/views.py
from django.shortcuts import render
from django.db import connection
from django.shortcuts import redirect
from .forms import *

# Create your views here.
def daftar_level(request):
	response = {}

	with connection.cursor() as cursor:
		cursor.execute("SELECT * FROM LEVEL_KEANGGOTAAN")
		response["list_level"] = cursor.fetchall()

	return render(request, 'daftar_level.html', response)

def tambah_level(request):
	if (request.method == "POST"):
		form = LevelForm(request.POST)
		if(form.is_valid()):
			with connection.cursor() as cursor:
				nama_level = request.POST['nama_level']
				min_poin = request.POST['min_poin']
				deskripsi = request.POST['deskripsi']
				cursor.execute("INSERT INTO LEVEL_KEANGGOTAAN VALUES(%s, %s, %s)", [nama_level, min_poin, deskripsi])

			return redirect("/level/")

	form = LevelForm()
	response = {}
	response["level_form"] = form
	return render(request, 'tambah_level.html', response)

def update_level(request, nama):
	data = {}
	response = {}

	if (request.method == "POST"):
		form = LevelForm(request.POST)
		if (form.is_valid()):
			with connection.cursor() as cursor:
				nama_level = request.POST['nama_level']
				min_poin = request.POST['min_poin']
				deskripsi = request.POST['deskripsi']
				cursor.execute("UPDATE LEVEL_KEANGGOTAAN SET nama_level = %s, minimum_poin = %s, deskripsi = %s WHERE nama_level = %s", [nama_level, min_poin, deskripsi, nama])

			return redirect("/level/")

	with connection.cursor() as cursor:
		cursor.execute("SELECT * FROM LEVEL_KEANGGOTAAN K WHERE K.nama_level = %s", [nama])
		data_level = cursor.fetchone()

	data["nama_level"] = data_level[0]
	data["min_poin"] = data_level[1]
	data["deskripsi"] = data_level[2]

	form = LevelForm(data)
	print(form)
	response["level_form"] = form
	response["nama"] = nama

	return render(request, 'update_level.html', response)

def delete_level(request, nama):
	with connection.cursor() as cursor:
		cursor.execute("DELETE FROM LEVEL_KEANGGOTAAN K WHERE K.nama_level = %s", [nama])
	return redirect("/level/")

level/templates/daftar_level.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'level/css/style.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
{% endblock %}
{% block content %}
<div class="col-xs-12 container">
	<h1 class="title">Daftar Level Keanggotaan</h1>
	<br>
	<br>
	<table class="table">
		<thead>
		<tr>
			<th>No</th>
			<th>Nama Level</th>
			<th>Deskripsi</th>
			<th>Minimum Poin</th>
			{% if request.session.role == "Admin" %}
			<th>Edit</th>
			<th>Delete</th>
			{% endif %}
		<tr>
		</thead>

		<tbody id="data_level">
		{% for level in list_level %}
		<tr id="level_1">
			<td id="no">{{ forloop.counter }}</td>
			<td id="nama">{{ level.0 }}</td>
			<td id="deskripsi">{{ level.2 }}</td>
			<td id="min_poin">{{ level.1 }}</td>
			{% if request.session.role == "Admin" %}
			<td><a href="{% url 'level:update_level' nama=level.0 %}"><button class="btn btn-icon btn-info"><i class="fa fa-keyboard"></i></button></a></td>
			<td><a href="{% url 'level:delete_level' nama=level.0 %}"><button id="delete" data-toggle="modal" data-target="#delete-modal" class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></a></td>
			{% endif %}
			{% endfor %}
		</tr>
		</tbody>
	</table>
</div>
{% endblock %}

level/templates/tambah_level.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'level/css/style.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
{% endblock %}
{% block content %}
<body id="tambah_level">
	<div class="col-xs-12 container">
		<form id="form_level" action="{% url 'level:add_level' %}" method="POST">
			{% csrf_token %}
			<h1 class="title text-white">Level Up!!</h1>
			<br>
			<br>

			{% for form in level_form %}
			{{ form }}
			<br>
			{% endfor %}
			<br>
			<button class="btn btn-green" type="submit" value="Submit">Buat</button>
		</form>
	</div>
</body>
{% endblock %}

level/templates/update_level.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'level/css/style.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
{% endblock %}
{% block content %}
<body id="tambah_level">
	<div class="col-xs-12 container">
		<form id="form_level" action="{% url 'level:update_level' nama=nama %}" method="POST">
			{% csrf_token %}
			<h1 class="title text-white">Level Up!!</h1>
			<br>
			<br>

			{% for form in level_form %}
			{{ form }}
			<br>
			{% endfor %}
			<br>
			<button class="btn btn-green" type="submit" value="Submit">Update</button>
		</form>
	</div>
</body>
{% endblock %}