barang/urls.py
from django.urls import path
from .views import *
#url for app

app_name = 'barang'
urlpatterns = [
    path('', daftar_barang, name='daftar_barang'),
	path('tambah_barang', tambah_barang, name='tambah_barang'),
    path('<kunci>/detail_barang', detail_barang, name='detail_barang'),
	path('<kunci>/update_barang', update_barang, name='update_barang'),
	path('<kunci>/delete_barang', delete_barang, name='delete_barang')
]

chat/urls.py
from django.urls import path
from .views import *
#url for app

app_name = 'chat'
urlpatterns = [
    path('', chat, name='chat'),
]

level/urls.py
from django.urls import path
from level import views

app_name = 'level'
urlpatterns = [
	path('', views.daftar_level, name='list_level'),
	path('add', views.tambah_level, name='add_level'),
	path('<nama>/update', views.update_level, name='update_level'),
	path('<nama>/delete', views.delete_level, name='delete_level')
]

pesanan/urls.py
from django.urls import path
from pesanan import views

app_name = 'pesanan'
urlpatterns = [
	path('', views.daftar_pesanan, name='daftar_pesanan'),
    path('buat_pesanan', views.buat_pesanan, name='buat_pesanan'),
    path('<int:pk>/update', views.update_pesanan, name='update_pesanan')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    url(r'^pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
    path('barang/', include('barang.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('chat/', include('chat.urls')),
    url(r'^item/', include(('item.urls', 'item'), namespace='item')),
    path('level/', include('level.urls')),
    path('pesanan/', include('pesanan.urls')),
    url(r'pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Toys Rent Padil</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if request.session.role == None %}
        <meta http-equiv = "refresh" content = "0; url = /" />
    {% endif %}
    {% block meta %}{% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
    {% block css %}{% endblock %}
</head>
<body>
    <div class="base-admin">
        <nav class="navbar navbar-expand-sm navbar-dark fixed-top">
            <a class="navbar-brand mx-2" href="#">
                <img src="{% static "img/logo.png" %}" alt="Logo" style="width:100px;">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse p-2" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link Font-Size-15" href="/pengguna/profil">Profil</a>
                    </li>
                    {% if request.session.role == "Admin" %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle Font-Size-15" href="#" id="navbardrop" data-toggle="dropdown">
                                Item
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item Font-Size-15" href="/item/tambah">Tambah Item</a>
                                <a class="dropdown-item Font-Size-15" href="/item">Daftar Item</a>
                            </div>
                        </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle Font-Size-15" href="#" id="navbardrop" data-toggle="dropdown">
                            Barang
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item Font-Size-15" href="{% url 'barang:tambah_barang' %}">Tambah Barang</a>
                            <a class="dropdown-item Font-Size-15" href="{% url 'barang:daftar_barang' %}">Daftar Barang</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle Font-Size-15" href="{% url 'level:list_level' %}" id="navbardrop" data-toggle="dropdown">
                            Level
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item Font-Size-15" href="{% url 'level:add_level' %}">Tambah Level</a>
                            <a class="dropdown-item Font-Size-15" href="{% url 'level:list_level' %}">Daftar Level</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle Font-Size-15" href="#" id="navbardrop" data-toggle="dropdown">
                            Pesanan
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item Font-Size-15" href="{% url 'pesanan:buat_pesanan' %}">Buat Pesanan</a>
                            <a class="dropdown-item Font-Size-15" href="{% url 'pesanan:daftar_pesanan' %}">Daftar Pesanan</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle Font-Size-15" href="#" id="navbardrop" data-toggle="dropdown">
                            Pengiriman
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item Font-Size-15" href="#">Buat Pengiriman</a>
                            <a class="dropdown-item Font-Size-15" href="#">Daftar Pengiriman</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link Font-Size-15" href="{% url 'chat:chat' %}">Chat Dengan Pengguna</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link Font-Size-15" href="/">Daftar Review Barang</a>
                    </li>
                </ul>
                <div><p class="nav-link Font-Size-15 p-0 m-0 mx-3" href="/">Admin</p></div>
                <div><a class="nav-link Font-Size-15 Logout" href="/pengguna/logout">Log&nbsp;Out</a></div>
            </div>
            {% elif request.session.role == "Anggota" %}
                    <li class="nav-item">
                        <a class="nav-link Font-Size-15" href="/item">Daftar Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link Font-Size-15" href="{% url 'barang:daftar_barang' %}">Daftar Barang</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle Font-Size-15" href="#" id="navbardrop" data-toggle="dropdown">
                            Pesanan
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item Font-Size-15" href="{% url 'pesanan:buat_pesanan' %}">Buat Pesanan</a>
                            <a class="dropdown-item Font-Size-15" href="{% url 'pesanan:daftar_pesanan' %}">Daftar Pesanan</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle Font-Size-15" href="#" id="navbardrop" data-toggle="dropdown">
                            Pengiriman
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item Font-Size-15" href="#">Buat Pengiriman</a>
                            <a class="dropdown-item Font-Size-15" href="/pengiriman">Daftar Pengiriman</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link Font-Size-15" href="{% url 'chat:chat' %}">Chat dengan admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link Font-Size-15" href="/review">Daftar Review Barang</a>
                    </li>
                </ul>
                <div><p class="nav-link Font-Size-15 p-0 m-0 mx-3" href="/">Anggota</p></div>
                <div><a class="nav-link Font-Size-15 Logout " href="/pengguna/logout">Log&nbsp;Out</a></div>
            {% endif %}
            </div>
        </nav>
    </div>
    {% if request.session.role != None %}
        {% block content %}
        {% endblock content %}
    {% endif %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>